cacheFolder: "${HOME}/.yarn/cache"

enableColors: true

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0004
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v2.4.0/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
